### ISSUE TITLE
Unity problem

### ISSUE THREAD

**Issue by maxovitsj** [cemdervis/SharpConfig#10]
I'm trying to install SharpConfig via NuGet using: Install-Package sharpconfig

and it throws this error:

Could not install package 'sharpconfig 1.4.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5,Profile=Unity Subset v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'm not sure how to fix this.

EDIT: 1.4.3 installed fine so I guess something changed in the latest version?

**Comment by cemdervis** [comment]
I can't recall changing anything from 1.4.3 to 1.4.4 regarding NuGet. Let me check when I get home.

**Comment by cemdervis** [comment]
Hey, if it still matters: I just released SharpConfig 1.4.6 on GitHub and NuGet. Should work now.

**Comment by maxovitsj** [comment]
Cool thanks
