### ISSUE TITLE
How to update existing section from object?

### ISSUE THREAD

**Issue by e4rthdog** [cemdervis/SharpConfig#101]
Is there any way to update an existing section in the file from a class?

I am currently doing this:

```
            cfg.RemoveAllNamed("MAIN");
            cfg.Add(Section.FromObject("MAIN", _config));
            cfg.SaveToFile("config.cfg");
```
Is this the preffered way?

**Comment by cemdervis** [comment]
Hi @e4rthdog,

the preferred way is to use the GetValuesFrom() method. Example:

`cfg["MAIN"].GetValuesFrom(_config)`

This updates the section named "MAIN" using the values stored in the **_config** object.
Note that you normally don't have to add any sections. When you write something like cfg["MAIN"], the section is automatically created for you (only if it doesn't exist yet).

**Comment by e4rthdog** [comment]
> Hi @e4rthdog,
> 
> the preferred way is to use the GetValuesFrom() method. Example:
> 
> `cfg["MAIN"].GetValuesFrom(_config)`
> 
> This updates the section named "MAIN" using the values stored in the **_config** object.
> Note that you normally don't have to add any sections. When you write something like cfg["MAIN"], the section is automatically created for you (only if it doesn't exist yet).

What you describe also updates the text file without having to call `SaveToFile `?

**Comment by cemdervis** [comment]
No, you still have to call SaveToFile() for that. So the full code would be:
```
cfg["MAIN"].GetValuesFrom(_config);
cfg.SaveToFile("config.cfg");
```

**Comment by e4rthdog** [comment]
Perfect. Thanks!

**Comment by cemdervis** [comment]
Sure thing!
