### ISSUE TITLE
long value?

### ISSUE THREAD

**Issue by znyet** [cemdervis/SharpConfig#105]
how to get a long value

**Comment by cemdervis** [comment]
Please provide an example configuration and C# code of what you want to achieve.

**Comment by znyet** [comment]
var config = Configuration.LoadFromFile("sample.cfg");
var section = config["General"];
var val = config["General"].LongValue;  //want to get an long value
LongValue support？

**Comment by cemdervis** [comment]
There is not LongValue property at the moment. Just use section["time"].GetValue<long>().
