### ISSUE TITLE
Where do you put the config file ?

### ISSUE THREAD

**Issue by Huaoe** [cemdervis/SharpConfig#106]
Hi,

Obvious question maybe but where and how to put config.cfg ?

Cheers,
Thomas

**Comment by cemdervis** [comment]
Hi @Huaoe, you put the file wherever you want, just like you would with any C# application. Just specify its correct path when using Configuration.LoadFrom...() methods.

**Comment by cemdervis** [comment]
Since there hasn't been any activity on this issue, I'll close it for now.
