### ISSUE TITLE
Serialization of arrays to objects (mapping)

### ISSUE THREAD

**Issue by noXur** [cemdervis/SharpConfig#11]
Hey there!

another problem I've noticed today:

+ The method `Section.FromObject()` does not consider arrays, so that it just stores the name of the type and not the array values.

+ In addition, it should be considered to ignore custom types (classes) at all during automatic serialization. Currently, it creates settings which also store just the name of the type.

**Comment by cemdervis** [comment]
@first problem: Oops, you're correct. Will implement that accordingly.
@second problem: What exactly do you mean?

**Comment by noXur** [comment]
@second: When an object which have got public fields made up of class types (for example, `CustomClass`) gets serialized with `Section.FromObject()`, then, the config file ends up with settings like this:

```
[ExampleSection]
CustomClass=CustomClass
```

**Comment by cemdervis** [comment]
I see, but that's the point of the serialization process; every value gets transformed using ToString().
A solution would be to use the proposed Ignore attribute, which will be available in the upcoming version. This way you can ignore entire types by declaring them on the type declaration, or you can partially ignore properties on custom types by declaring the attribute there.

Example 1:
```csharp
// This type is ignored entirely by the (de)serialization process.
[SharpConfig.Ignore]
class MyType
{ }
```

Example 2:
```csharp
// Here, only the Age property is ignored during (de)serialization.
class MyType
{
    public string Name { get; set; }

    [SharpConfig.Ignore]
    public int Age { get; set; }
}
```
