### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#111]
Hi,

This is the Sample.ini file...

[Google]
Pattern="\d{4}/\d{2}/\d{2}-\d{2}:\d{2}:\d{2}-UTC"
Parse="yyyy/M/d-H:m:s-UTC"
Format="yyyy/MM/dd-HH:mm:ss-IST"
FormatDMY="dd/MM/yyyy-HH:mm:ss-IST"

[Instagram]
Pattern="\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC"
Parse="yyyy-M-d H:m:s UTC"
Format="yyyy-MM-dd HH:mm:ss IST"
FormatDMY="dd-MM-yyyy HH:mm:ss IST"

and this is the sample code...

```
using System;

namespace Checking
{
    class Program
    {
        static void Main(string[] args)
        {
            var cfg = SharpConfig.Configuration.LoadFromFile("Sample.ini");

            for (int i = 0; i < cfg.SectionCount; i++)
            {
                Console.WriteLine(cfg[i].Name);
            }
        }
    }
}
```

The output is...

**$SharpConfigDefaultSection**
Google
Instagram

Why the first/default section is returned???

Thanks

**Comment by Ketan-Desai** [comment]
Please use this attached Sample.ini, since there seems some markup issue.

[Sample.zip](https://github.com/cemdervis/SharpConfig/files/6378149/Sample.zip)

**Comment by cemdervis** [comment]
Hi,
because the default section (which is the global section) is part of the section collection. If you want to avoid it during iteration, just check if its name is equal to `Section.DefaultSectionName`. Let me know if that helped.

**Comment by Ketan-Desai** [comment]
Hi Cemalettin,

Yes, it worked.

Thanks for the prompt reply and awesome library :)

**Comment by cemdervis** [comment]
You're welcome
