### ISSUE TITLE
CreateObject / FromObject issue.

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#15]
Sir,

The issue is related to DateTime field.

While using CreateObject and FromObject methods, if the system date and time settings are different then DateTime field parsing might fail and throw exception.

Is it possible to provide format string or something via field/property attributes?

Thanks

**Comment by cemdervis** [comment]
Hey there, sorry for the late reply!

That's certainly possible, but needs more planning than I think. I'm rather busy at the moment, but I would look into this problem in about a week. Of course, help is appreciated!

**Comment by cemdervis** [comment]
What do you mean by 'different'? The CultureInfo? Or different value?

**Comment by Ketan-Desai** [comment]
Different CultureInfo.

If same application is used in PCs having different CultureInfo, then ini file written in one PC (using CreateObject) can't be read in another (using FromObject) due to different CultureInfo.

**Comment by cemdervis** [comment]
Alright, I'll be fixing that.

**Comment by Ketan-Desai** [comment]
Sir,

Thank you very much for such a nice library, it's awesome :)

**Comment by cemdervis** [comment]
You're welcome! The new version (1.5.1) is up, which should fix this issue.
