### ISSUE TITLE
T Setting.GetValueTyped<T>(); exception

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#18]
Sir,

Please refer following code snippet, the exception is in LoadConfig().
It used to work in prior versions.

class Program
    {
        static void Main(string[] args)
        {
            SaveConfig();
            LoadConfig();
        }

        static void SaveConfig()
        {
            var cfg = new Configuration();
            cfg["Setting"]["Gender"].SetValue<Gender>(Gender.Male);

            cfg.SaveToFile("Sample.ini");
        }

        static void LoadConfig()
        {
            var cfg = Configuration.LoadFromFile("Sample.ini");

            // Exception!
            Gender gender = cfg["Setting"]["Gender"].GetValueTyped<Gender>();
        }
    }

    public enum Gender
    {
        Male,
        Female,
    }

**Comment by cemdervis** [comment]
Alright, it's fixed. New version will be up shortly.

**Comment by cemdervis** [comment]
New version (1.5.2) is up. Thank you very much for the find!
