### ISSUE TITLE
Exception if configuration is saved to a non-existing file inside non-existing folder.

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#20]
string fileName = @"D:\Folder\File.ini";

// Exception if D:\Folder not exist.
cfg.SaveToFile(fileName);

**Comment by Ketan-Desai** [comment]
My mistake, the behavior is same for System.IO.File.xxx functions.

**Comment by cemdervis** [comment]
Yeah, you have to ensure that the directory exists first, by using Directory.CreateDirectory().
