### ISSUE TITLE
Check if section / key exist

### ISSUE THREAD

**Issue by bartolije** [cemdervis/SharpConfig#21]
Hey,

Is there any ways to check easily if a section, or a key exist?
Included into this awesome libs, or on my side?

EDIT: Found my issue.
I got an error on:
`bool move = conf["Settings"]["move"].BoolValue`
saying the instance isn't define to an object.

I fixed it on my side by making a weird workaround, such as:
`bool move = Convert.ToBoolean(conf["Settings"]["move"].StringValue);`

**Comment by cemdervis** [comment]
Hey there!
Sure, you can check if a section or setting exists using the Contains method.
The Configuration class has a Contains(string sectionName) and Contains(Section section) method.
The Section class also has these methods, but for settings.

Could you explain the error please?

```csharp
bool move = conf["Settings"]["move"].BoolValue
```

What exactly is not working here?

Cheers!

**Comment by bartolije** [comment]
Okay, thank you very much.

I got an error saying the instance isn't define to an object. (object conf)
All working fine when with convert string to bool

**Comment by cemdervis** [comment]
You're welcome. Do you have an example for 'conf', so I can test it? Maybe there's a bug within SharpConfig. Thank you!

**Comment by bartolije** [comment]
Sure.
Here what I got.

First, let's say on first launch, i'll create the file. (INIFILE = my file name as string)
replaceScript and moveScript are bool value, loaded from GUI. (define, 100% sure and checked not null or different than true/false)

```
Configuration conf = new Configuration();
conf["Settings"]["replace"].BoolValue = replaceScript;
conf["Settings"]["move"].BoolValue = moveScript;
conf.SaveToFile(INIFILE);
```

Later, or after a reload, I need to get these settings.

Configuration conf = Configuration.LoadFromFile(INIFILE);
replaceScript = conf["Settings"]["replace"].BoolValue;
moveScript = conf["Settings"]["move"].BoolValue;

At this point, into a try catch, got error like "instance (so conf) isn't set to an object.
Here a screenshot of my VisualStudio debug case (sorry language)
[http://i.imgur.com/GuvkgAW.png](url)

**Comment by cemdervis** [comment]
Alright, it was a bug in SharpConfig. I've already fixed it and will submit a new version with various other fixes in a few minutes.

**Comment by bartolije** [comment]
Okay.
Thank you a lots for that fix, awesome :)

#ClosedIssue

**Comment by cemdervis** [comment]
Alright, the new version (1.5.3) is up.
Cheers! :)
