### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#22]
Sir,

The android API have concept of SharedPreferences, where you can put application settings. (just like ini), and it have methods like: boolean getBoolean (String key, boolean defValue);

The "defValue" is really useful in case the key/setting does not exist.

I suggest if it can be implemented in SharpConfig...

Like following code will throw exception.

            var cfg = new Configuration();

            bool isWar = cfg["Rocket"]["Fire"].BoolValue;

Instead it'll be better if we can pass default value, so that it will not be necessary to check if section/setting already exist?

Thanks

**Comment by cemdervis** [comment]
Hey there!

A feature such as this is already implemented in SharpConfig.
You just have to get the setting value as a nullable type.
So for your example it would be something like:
```csharp
var cfg = new Configuration();
bool? isWar = cfg["Rocket"]["Fire"].GetValue<bool?>();
bool theRealValue = isWar.GetValueOrDefault(false);
```

in short:
```csharp
bool isWar = cfg["Rocket"]["Fire"].GetValue<bool?>().GetValueOrDefault(false);
```

Cheers!

**Comment by Ketan-Desai** [comment]
Sir,

Thanks, it's just awesome :)

**Comment by cemdervis** [comment]
You're welcome!
