### ISSUE TITLE
API feature request...

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#23]
Sir,

For now, we are following this pattern to add/access sections...

Section section = new Section("Sample");
Configuration.Add(section);

It might be helpful to add following support...

Section section = Configuration.Add("Sample");

i.e. Add following API...
Section Configuration.Add(string name);

and similar for Setting class too.

Thanks

**Comment by cemdervis** [comment]
This seems a bit redundant, as you can already use the Section getter of Configuration for this.
```csharp
Section section = Configuration["Sample"];
```

This will create a section called "Sample" automatically, if it does not exist yet.
Otherwise it will return the already existing section.

Cheers!

**Comment by Ketan-Desai** [comment]
Thanks again.

On Thu, Apr 21, 2016 at 2:55 AM, Cemalettin Dervis <notifications@github.com
