### ISSUE TITLE
FormatOfLeadingComment

### ISSUE THREAD

**Issue by KlausWilly** [cemdervis/SharpConfig#24]
Hello Cemalettin;

First of all: thank's for your pretty nice helper.
it' working very well.

I tested it a bit a found one problem:
I have an ini with a leading Comment.
It is read from Disk ok, but when i write it to Disk then there is a problem with the Line-ending.
You can only see it in a hex-editor, texteditors correct it automatically.
In the leading Comment is only a linfeed (\n) appended and not a CR\LF (\r\n)
I think the problem is in file "setting.cs" line 528 + 540
   return string.Format("{0}\n{1}={2}" should be  return string.Format("{0}\r\n{1}={2}",
But i haven't tested it.

May be you can look for?

thanks a lot
best regards 
Klaus

**Comment by cemdervis** [comment]
Hey Klaus, thanks and you're welcome!
That's actually correct and a big mistake, as it shouldn't be \n **and also not** \r\n, but rather Environment.NewLine [(which is \r\n on Windows, and corresponding on other platforms)](http://stackoverflow.com/questions/1015766/difference-between-n-and-environment-newline).
I will fix that, thank you for the hint.

Cheers!

**Comment by cemdervis** [comment]
Alright, it's fixed by the new version, 1.5.4!
