### ISSUE TITLE
Comments in existing ini file are striped after save

### ISSUE THREAD

**Issue by ntodorov** [cemdervis/SharpConfig#3]
I've noticed that if I load an ini file with comments, then save all comments are lost.
Is this by design?

**Comment by cemdervis** [comment]
Hi,
yes, that is by design. It's easily possible to implement that feature though.

**Comment by cemdervis** [comment]
Hey,
sorry, I just looked at and tested the code. I didn't see any comment loss.
How can I reproduce your problem?

**Comment by ntodorov** [comment]
Yep exactly those. I have some configurations that are manged by hand and there are alot of 
;
;Application configurations
;
[xxx]
...

;
;WebApp configurations
;

and I cannot lose those.

**Comment by cemdervis** [comment]
I've just released a new version (1.4.1) which solves this problem.
