### ISSUE TITLE
Some comment corrections and suggestions...

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#30]
Sir,

In Configuration.DateTimeFormat comment, it should be CultureInfo.InvariantCulture.DateTimeFormat rather then CultureInfo.InvariantCulture.NumberFormat?

Is it possible to specify separator in xxxArray(), it looks default is comma.
Something like Configuration.ValidCommentChars?

Incase of string array, if string contains ',' then it might cause issue?

**Comment by cemdervis** [comment]
Hey Ketan-Desai,

thanks for the comment correction!
Well yes, comma is the default array element separator; your proposal seems reasonable.
Expect a new release soon.

Cheers!

**Comment by cemdervis** [comment]
Fixed with version 2.0.1.
