### ISSUE TITLE
Can't read the file on another app - Unity

### ISSUE THREAD

**Issue by rpassareti** [cemdervis/SharpConfig#32]
Hi, I will try to explain what is my plan, and what is happening

I'm developing two app's that will work together, one simple app, and another with videos and gear vr
on the first app it creates a file, with names, the second app would read this file, and execute the videos and informations

I can see the file, but when I tried to read it, it gives null values, but i can change the values!
like:
on the first app I say: cfg["Person]["Name].SetValue("John");
when I go to the second app, i can't read the name "John", but I can change it to anything else
BUT can't read it either
when I ask to debug the value, it gives me a null value, and when I open the file, shows me the modification

any solution?

**Comment by cemdervis** [comment]
Hey there, have you made sure that the config file exists when loading it?
And could you please show some code of how you load the config?

**Comment by rpassareti** [comment]
yes, everything is like your code
i will post the code, and some prints

app1:
````c#
//start of app
    void Start()
    {
        if (!File.Exists(Application.persistentDataPath + "/dttchld1.cfg"))
        {
            Debug.Log("Setting up a default config since no file was found!");
            SetupCleanCFG();
            SaveConfig();
        }
        else
        {
            Debug.Log("already exist");
            cfg = Configuration.LoadFromFile(Application.persistentDataPath + "/dttchld1.cfg");
            LoadConfig();
        }
        Debug.Log(Application.persistentDataPath);
        cfg = Configuration.LoadFromFile(Application.persistentDataPath + "/dttchld1.cfg");
    }

    //setting the file
    public void SetupCleanCFG()
    {
        cfg["Video"]["nome"].SetValue(videoCarregado);

        Debug.Log(cfg["Video"]["nome"].StringValue);

        videoCarregadoSalvo = cfg["Video"]["nome"].StringValue;

        Debug.Log("Video Salvo: " + videoCarregadoSalvo);
    }

    public void SaveConfig()
    {
        cfg.SaveToFile(Application.persistentDataPath + "/dttchld1.cfg");
    }
````

img of app1:
http://imgur.com/a/OeG94

--

app2:
````c#
  //setting the path of the file created on app1
   public static string GetDownloadFolder()
    {
        string[] temp = (Application.persistentDataPath.Replace("Android", "")).Split(new string[] { "//" }, System.StringSplitOptions.None);

        return (temp[0] + "/Android/data/com.vc2b.disney3602app/files/");
    }
  //start of the app
    void Start()
    {
        GetDownloadFolder();
        Debug.Log(GetDownloadFolder());
        Debug.Log(GetDownloadFolder() + "dttchld1.cfg");

        DATA_FILE = GetDownloadFolder();

        if(File.Exists(DATA_FILE))
        {
            Debug.Log("Existe essa pasta");
        }

        if (!File.Exists(Application.persistentDataPath + "/dttchld2.cfg"))
        {
            Debug.Log("cria arquivo");
            cfg = Configuration.LoadFromFile(DATA_FILE + "dttchld1.cfg");
            Load();
        }
        else
        {
            Debug.Log("carrega oq existe");
            cfg2 = Configuration.LoadFromFile(Application.persistentDataPath + "/dttchld2.cfg");
            LoadName();
        }
        StartCoroutine( Setup());
    }

    IEnumerator Setup()
    {
        yield return new WaitForSeconds(5f);
        cfg3["Video"]["nome"].SetValue("testando ver se consegue pegar isso");
        cfg.SaveToFile(Application.persistentDataPath + "/dttchld3.cfg");

        Debug.Log(cfg3["Video"]["nome"].StringValue);
    }

   public void Load()
    {
        if (!File.Exists(DATA_FILE + "dttchld1.cfg"))
        {
            Debug.Log("não existe");
        }
        else
        {
            Debug.Log("achou");
            cfg2["Video"]["nome"].SetValue(cfg["Video"]["nome"].StringValue);

            cfg2.SaveToFile(Application.persistentDataPath + "/dttchld2.cfg");
           
            LoadName();
        }
    }
    void LoadName()
    {
        videosName = cfg2["Video"]["name"].StringValue;
        Debug.Log("VideosName: " + videosName);
        Debug.Log("Antes de atualizar: " + cfg2["Video"]["name"].StringValue);
    }
````
img app 2: http://imgur.com/a/pS5kY


I don't know if it changes anything, but it's for Android

**Comment by cemdervis** [comment]
Hey, you are using SharpConfig correctly, so I assume that there is a problem with the logic of your apps. Have you checked if the config filename is the same in app1 **and** app2?

Because in app1 you are saving the config as:
```csharp
cfg.SaveToFile(Application.persistentDataPath + "/dttchld1.cfg");
```

And then in app2 you are loading dttchld1.cfg, but the path is not the same.
Look at Start() of app2:
```csharp
DATA_FILE = GetDownloadFolder();
// ...
cfg = Configuration.LoadFromFile(DATA_FILE + "dttchld1.cfg");
```

Where DATA_FILE will be the result of:
```csharp
public static string GetDownloadFolder()
{
    string[] temp = (Application.persistentDataPath.Replace("Android", "")).Split(new string[] { "//" }, System.StringSplitOptions.None);
    return (temp[0] + "/Android/data/com.vc2b.disney3602app/files/");
}
```

Which is **not** the same as the path of app1 (Application.persistentDataPath + "/dttchld1.cfg").

Otherwise there should be no problem with SharpConfig, as it uses the built-in System.IO libraries of .NET.
Please note that when you are inspecting values of the config through the debugger, they may not exist, because SharpConfig uses [lazy evaluation](https://en.wikipedia.org/wiki/Lazy_evaluation), so the values will only be created when you are accessing them directly (in code).

But this should never cause the problems you have, that's why I assume there must be something in your app(s).

Let me know if that helped,
Cheers!

**Comment by rpassareti** [comment]
OMG! I CAN'T BELIVE!
IT WORKS!!!!

I tested your edited post, and yeah, it was my mistake, putting other name on the settings!
thx a lot! and sry for being a newbie and didn't saw this little mistake!

thx a lot!!!!

**Comment by cemdervis** [comment]
Hey there! No problem, glad it's fixed 👍 

Cheers!
