### ISSUE TITLE
Compile Error in Unity: Feature 'nameof operator' is not available in C# 4

### ISSUE THREAD

**Issue by haraldini** [cemdervis/SharpConfig#36]
Followed instructions at https://github.com/cemdervis/SharpConfig/wiki/How-to-quickly-get-this-up-and-running-in-Unity

but it throws the following error
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8025	Feature 'nameof operator' is not available in C# 4.  Please use language version 6 or greater.	xmas-kinect.CSharp.Plugins Assets\Plugins\SharpConfig\Section.cs	127	Active
`

**Comment by cemdervis** [comment]
Fixed with latest commit, thanks for reporting.
