### ISSUE TITLE
Section.Remove suggestion...

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#39]
Hi,

In .NET API, like File.Delete, If the file to be deleted does not exist, no exception is thrown.
Similarly, Section.Remove() should not throw exception if not exist?

Since, many times it is required to remove sections that might not exist.
But Section.Contains() call is always required for checking.

Thanks

**Comment by cemdervis** [comment]
Hey,
this behaviour was chosen to be consistent with the .NET API (e.g. List, Dictionary etc.).
You should not have to use Remove() so often that this would be a problem.
Are there .NET containers that **don't** throw when trying to remove a non-existent element?

Cheers!

**Comment by cemdervis** [comment]
After evaluation, changing Remove to not throw makes more sense in this case. Expect it with the next release.

**Comment by cemdervis** [comment]
Fixed with version 2.1.

**Comment by Azhe403** [comment]
please code sample.. in c#
