### ISSUE TITLE
Configuration.Save() adds space before and after the key value delimiter (=)

### ISSUE THREAD

**Issue by ntodorov** [cemdervis/SharpConfig#4]
My understanding is that is better to keep the ini file to its original design:
http://en.wikipedia.org/wiki/INI_file

Key=value is almost always with no space in my experience and some tools or programs will choke on those spaces.

Also it will be better for existing files  to be kept in their original condition as much as possible.

Example:
[section 1]
app=bbb

after Configuration loads it and save's it back it will be:

[section 1]
app = bbb

BTW - I'm enjoying SharpConfig :) good job!

**Comment by cemdervis** [comment]
Thanks!
I see. The "problem" lies in [Setting](https://github.com/cemdervis/SharpConfig/blob/master/SharpConfig/Setting.cs#L314)'s ToString method. Will be fixed, thanks for the advice!

**Comment by cemdervis** [comment]
Alright, it's fixed with the current version (1.4.2).

**Comment by ntodorov** [comment]
You are realy fast! :) thanks! I have forked the repo in case you do not have time to fix it my self and send pull request but it seems no need.
