### ISSUE TITLE
Section.Remove related...

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#40]
Hi,

v2.1.0 contains following code in Section.cs...

```
        public bool Remove(Setting setting)
        {
            if (setting == null)
                throw new ArgumentNullException("setting");

            if (mSettings.Contains(setting))
            {
                mSettings.Remove(setting);
                return true;
            }
            else
                return false;
        }

```
Is it correct to modify as...

```
        public bool Remove(Setting setting)
        {
            if (setting == null)
                throw new ArgumentNullException("setting");

                return mSettings.Remove(setting);
        }

```
ref. https://msdn.microsoft.com/en-us/library/cd666k3e(v=vs.110).aspx

and also, if it is true, then similar changes can be applicable else-where in the code base?

**Comment by cemdervis** [comment]
Hey, that's indeed correct. Even the null check can be removed, as List accepts null references, I didn't know that. Thanks for showing it, will be changed.
