### ISSUE TITLE
StringValueArray does not parse arrays with apostrophes

### ISSUE THREAD

**Issue by barbedCoil** [cemdervis/SharpConfig#47]
Here is a sample bit of code that was a bit puzzling - I have an .ini section [TestRun] with a string array with one of the array values having an apostrophe - when I step through the code (see below .ini entries) the StringValueArray returns a null.

Removing the apostrophe (see 2nd [TestRun] section) then StringValueArray parses properly.

**I did not see any exceptions to using StringValueArray and wondered why an apostrophe would create a problem - is this fixable?**
`
; fails to parse - StringValueArray returns null but there is an error that is not thrown
[TestRun]
Test = {010|Store A, 020|Store's We Like, 30|Stores We Do Not Like}

; parses fine - Only difference from previous is apostrophe for 020|...
[TestRun]
Test = {010|Store A, 020|Stores We Like, 30|Stores We Do Not Like}

Section test = config["Test"];
string[] _test = test["Test"].StringValueArray;
`

**Comment by cemdervis** [comment]
Hey there,
this is not a parsing error, but a data error. I forgot to remove '\'' as a valid comment char.
Thus, SharpConfig will parse everything after the apostrophe as a comment.
You can verify this by looking at the setting's Comment property value.
This will be fixed ASAP, thanks for reporting it.

**Comment by barbedCoil** [comment]
Thanks! Make sense
