### ISSUE TITLE
Can I use '#' in my value?

### ISSUE THREAD

**Issue by ailncode** [cemdervis/SharpConfig#49]
Like this
password = x123#
and then SharpConfig give me password x123

**Comment by cemdervis** [comment]
Just place quotes around the value: `password = "x123#"`
This will give you the exact string value `"x123\#"`
After that, trim the string to remove the quotes.
Example: `string pw = cfg["general"]["password"].StringValue.Trim('\"');`

**Comment by ailncode** [comment]
thanks.

**Comment by znyet** [comment]
thank you。
string pw = cfg["general"]["password"].StringValue.Trim('\"');  it can solve the read problem.
but if you want write to the file,Example:
string sql="database=test;uid=sa;pwd=123";
int the sample.int file
[group]
sql=database=test;uid=sa;pwd=123
it is wrong.

**Comment by cemdervis** [comment]
What exactly is wrong in this case?

**Comment by znyet** [comment]
I‘m so sorry，I'm chinese.so I can speek a little english;
When I have a string, it like 
string sql="database=test;uid=sa;pwd=123" in c# code;
and I using your dll method,and want to save it to the file. and I save successfully.
but int the file,the sql become like this
[group]
sql=database=test;uid=sa;pwd=123
and I can't read sql settingnode anaymore;

**Comment by cemdervis** [comment]
No problem. So your settings are "database", "uid" and "pwd"?
If so, you have to separate them in the config file. Your config file should look like this:
```
[group]
database = test
uid = sa
pwd = 123
```
And then read it in C# like this:
```csharp
var database = cfg["group"]["database"].StringValue;
var uid = cfg["group"]["uid"].StringValue;
var pwd = cfg["group"]["pwd"].StringValue;
```

Let me know if that helped.
