### ISSUE TITLE
Configuration.ParseSetting(string line) trims text after ' " '

### ISSUE THREAD

**Issue by likemike91** [cemdervis/SharpConfig#5]
Hello!

I have an ini file with ' " ' a value of a setting.
But Configuration.ParseSetting(string line) trims every text which is coming afterwards.

Example:

[General]
MySetting=DataSource="MyCustomDataSource;..."

The value of config["General"]["MySetting"] is "DataSource=" and the rest is removed.

Is there any solution for this problem?

**Comment by cemdervis** [comment]
Hi,

so you have a setting such as this one?:
SomeSetting = 'My"Value'

If that was wrong, could you give an example please?

**Comment by michaelhahn91** [comment]
I have updated my comment above. ;)

**Comment by cemdervis** [comment]
Oh I see! Yeah, SharpConfig is pretty naive if it comes to strings. It just trims everything after a comment char is detected. I'll fix that soon, thanks!

**Comment by michaelhahn91** [comment]
Okay thank you for your fast response!

**Comment by cemdervis** [comment]
No problem!

**Comment by cemdervis** [comment]
One way you can solve this problem is by modifying the static Configuration.ValidCommentChars value. The default value is { '#', ';', '\'' }. Just assign an array that contains all symbols you want to be treated as a comment delimiter, except the semi-colon. I'll work on a fix for the in a couple of days.

**Comment by likemike91** [comment]
Okay that would be an option too.

Do you have a suggestion for my problem if I have the following two entries in an external (can't change the structure or values) ini file (The comment with a semicolon and a connectionstring without quotation marks but containing also a semicolon):

;This is the connection string for the database
DataSourceNameX64=Provider=Microsoft.SQLSERVER.CE.OLEDB.4.0;Data Source="<<PathToDatabase>>"

**Comment by cemdervis** [comment]
Ignore my solution, I found the problem inside SharpConfig. SharpConfig was already aware of DB connection strings and ignored comment symbols inside strings, but the code had a bug. I just fixed it and will release a fix in 1-2 hours.

**Comment by likemike91** [comment]
Is the problem I've described above also fixed?

**Comment by cemdervis** [comment]
Yes, it will be fixed automatically since it was a side effect.

**Comment by likemike91** [comment]
Perfect. Thanks.

**Comment by cemdervis** [comment]
Hey, I just released the fixed version (1.4.3). Before parsing your configs, make sure to set the value of Configuration.IgnoreInlineComments to true.
That tells SharpConfig to ignore all comment chars that are in-line with settings when parsing.
The reason you have to do this is: your configuration structure seems to allow a semi-colon as a value that is NOT inside quotation marks. For example:

DataSourceNameX64=Provider=Microsoft.SQLSERVER.CE.OLEDB.4.0;Data Source="[Path]"

If this part: Microsoft.SQLSERVER.CE.OLEDB.4.0;Data Source="[Path]"
were inside quotation marks, you wouldn't have to set Configuration.IgnoreInlineComments to true.

Let me know if that helped!

**Comment by likemike91** [comment]
I will try it tomorrow when I'm in the office again.
But I 
think now it will work.
Thank you for the fast fix. :)

**Comment by likemike91** [comment]
I have tried it now and it worked like a charm.
Thank you again!

**Comment by cemdervis** [comment]
You're welcome!
