### ISSUE TITLE
Section indexer related

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#50]
Hi,

```
            var cfg = new Configuration();

            var sectionA = cfg["A"];
            var section1 = cfg[1];
```

The 2nd indexer throws exception, why not create section by calling ToString() on numeric value?

Thanks

**Comment by cemdervis** [comment]
Hey there, this is to ensure consistency across sections and settings; both are only addressed by their (string) key. The int indexer is used to get sections and settings by their zero-based index. It's not a key.
If you want to access a section named "1", you'd have to call ToString() yourself: `var section1 = cfg[num.ToString()]`.
