### ISSUE TITLE
Quoted arrays elements not working

### ISSUE THREAD

**Issue by DWilches** [cemdervis/SharpConfig#53]
Hello,

If I want to store in an array an element with spaces, my first guess was to put it within double quotes like this:

    Pets = { hamster, cat, mango, "some bird" }

But I found that SharpConfig interprets those quotes as being part of the 4th element. So:

    array[3] == "\"some bird\""

Instead of what I expected:

    array[3] == "some bird"

This also means I cannot put special characters inside the quoted elements, like for example a comma:

    Pets = { hamster, cat, mango, "some,,,bird" }

My use case is: the users of my app will put in that array some filenames they choose to. So they an have weird characters like `,` or `}`, so having a way of escaping them seemed reasonably to me.

**Comment by cemdervis** [comment]
Hi DWilches,

If an array element is quoted, SharpConfig will treat the double quotes and everything inside of them as part of the element value. That's intentional. If you don't need the double quotes, you may ```.Trim('\"')``` the value. But I'm not sure about your use case. SharpConfig gives me ```\"some,,,bird\"``` as the value, which is correct. Which value did you expect exactly?

**Comment by DWilches** [comment]
The actual value I tried inside the double quotes was: `{ "this contains , spaces" }` and SharpConfig returned an array with two elements: "\"this contains" and "spaces\"". Can it be the sapces around the `,` what gives problems? I can try again on Monday if this doesn't give the same result at your side.

**Comment by cemdervis** [comment]
Just to be clear, ultimately the value you're storing is: ```Pets = { hamster, cat, mango, "{ "this contains , spaces" }" }```. Correct? If so, I get the same values as you described, and it's indeed a bug in the parser. I'll look into it.

**Comment by DWilches** [comment]
No, the value I'm storing is:
`Pets = { hamster, cat, mango, "this contains , spaces" }`
And what I'm getting back from SharpConfig is:
`Pets[0] = "hamster"`
`Pets[1] = "cat"`
`Pets[2] = "mango"`
`Pets[3] = "\"this contains"`
`Pets[4] = "spaces\""`

**Comment by cemdervis** [comment]
That's odd, I'm getting the correct values, meaning:
```Pets[3] = "\"this contains , spaces\""```
Have you changed any of the static Configuration properties like Configuration.ArrayElementSeparator?
