### ISSUE TITLE
; separated values are read as 1 value + comment containing the rest

### ISSUE THREAD

**Issue by mahoganysatsuma** [cemdervis/SharpConfig#57]
Hi,

I'm reading an ini file which contains both comments with a ';' and ';' separated list values like this:

; Pre-section comment
[Section]
setting=value1;value2;value3

I end up with a Section with the correct PreComment, but my setting StringValue is "value1", and the setting Comment is "value2;value3".

Is there a way where I can get the setting value to actually be "value1;value2;value3"? I can workaround to concatenate my stringvalue and comment separated by a ';' but that doesnt feel right at all. So maybe i'm doing something silly, maybe you can add this as a feature? (e.g. RawValue without any comment logic?)

Thanks.

**Comment by mahoganysatsuma** [comment]
I was probably too quick in thinking this couldn't be done, but then i found "public static bool IgnoreInlineComments { get; set; }" in your API :) If i use that it works as intended for my use case. Guess you can close this!

**Comment by cemdervis** [comment]
Hey there, just wanted to answer, but it's nice that you already found a way. Another solution would be to change the comment delimiting characters using Configuration.ValidCommentChars. By default, it's {'#'. ';'}, but you could change it to just be ';' (or whatever you like). Assuming you have control over how the config files are generated, of course.
