### ISSUE TITLE
Request: Char array having Escape Sequences

### ISSUE THREAD

**Issue by Ketan-Desai** [cemdervis/SharpConfig#58]
Sir,

Feature request: Char array having Escape Sequences or Unicode Escape Sequences.

Thanks

**Comment by cemdervis** [comment]
Which char array? Do you have an example?

**Comment by Ketan-Desai** [comment]
char[] trimChars = { (char)160, '\n', '\r', '\t', (char)30, '\0' };

**Comment by cemdervis** [comment]
What do you want to trim?

**Comment by Ketan-Desai** [comment]
Um, No.

I want to save this kind of char array in an ini file.

**Comment by cemdervis** [comment]
I see, let me check.

**Comment by cemdervis** [comment]
Fixed with version 3.2.1.
