### ISSUE TITLE
Only write quoted setting values when necessary

### ISSUE THREAD

**Issue by cemdervis** [cemdervis/SharpConfig#60]
At the moment (3.3.2), setting values are always written to to a file inside quotes, even when it's not necessary. It was pointed out in issue #59 that this could lead to incompatibility with existing applications and / or legacy config files. Another hotfix should guarantee that values will only be quoted iff the value contains spaces or comment delimiting characters.

**Comment by cemdervis** [comment]
Fixed with version 3.2.3.

**Comment by mahoganysatsuma** [comment]
Unfortionately I can now no longer use "Configuration.IgnoreInlineComments = true", and https://github.com/cemdervis/SharpConfig/issues/57 is back. Maybe you can only check for spaces when quoting when Configuration.IgnoreInlineComments = true to not quote stuff with comments?

**Comment by mahoganysatsuma** [comment]
On a side note, ValidCommentChars only has a private set, otherwise i could use that as a work-around.

**Comment by cemdervis** [comment]
Could you give an example please?

**Comment by mahoganysatsuma** [comment]
Reading my ini file:
```
[Section]
Params=param1;param2;param3
```
as such:
```
Configuration.IgnoreInlineComments = true;
var config = Configuration.LoadFromFile(ConfigurationFilePath + IniConfigurationFilename);

string parameterArray = config["Section"]["Params"].StringValue;
```
results in parameterArray containing 'param1', but in 3.0.0 using the IgnoreInlineComments would contain 'param1;param2;param3'.



Saving a ; separated list as such:
```
Configuration.IgnoreInlineComments = true;
var config = Configuration.LoadFromFile(ConfigurationFilePath + IniConfigurationFilename);
config["Section"]["Params"].SetValue("param1;param2;param3");
config.SaveToFile(ConfigurationFilePath + "Copy.ini");
```
Will store as:
```
[Section]
Params="param1;param2;param3"
```

but i would prefer as i'm using ignoreinlinecomments to store it as 
```
[Section]
Params=param1;param2;param3
```
