### ISSUE TITLE
Configuration.IgnoreInlineComments is ignored

### ISSUE THREAD

**Issue by cemdervis** [cemdervis/SharpConfig#62]
As mentioned in issue #60, Configuration.IgnoreInlineComments ignored as of 3.2.3.
This is caused by the ConfigurationReader, which ignores the value of Configuration.IgnoreInlineComments once an inline comment is found. Example:
```
Params=param1;param2;param3
```
Params.StringValue will become "param1" instead of "param1;param2;param3", regardless of what value is set on Configuration.IgnoreInlineComments.

**Comment by cemdervis** [comment]
Fixed with version 3.2.4.

**Comment by mahoganysatsuma** [comment]
Reading works great again, thanks!

Is it possible to do the following change also (added a check for IgnoreInlineComments upon writing)?:

```
    private static string GetValueForOutput(string rawValue)
    {
      if (rawValue.StartsWith("{") && rawValue.EndsWith("}"))
        return rawValue;

      if (rawValue.StartsWith("\"") && rawValue.EndsWith("\""))
        return rawValue;

      if (
        (rawValue.IndexOf(" ") >= 0) ||
        ((rawValue.IndexOfAny(Configuration.ValidCommentChars) >= 0) && !(Configuration.IgnoreInlineComments)))
      {
        rawValue = "\"" + rawValue + "\"";
      }

      return rawValue;
    }
```
In this way I think reading/writing stuff with inline comments ignored is more consistent.

**Comment by cemdervis** [comment]
Good catch, that's correct. I'll put another hotfix up soon.
