### ISSUE TITLE
about array size is 0

### ISSUE THREAD

**Issue by bushadam** [cemdervis/SharpConfig#7]
in setting.cs
 // Read the last element.
                    values[i] = ConvertValue(
                        mRawValue.Substring(elemIndex, mRawValue.Length - elemIndex - 1),
                        elemType);
while throw exception
 change to 
 // Read the last element.
                if (this.ArraySize > 0)
                    values[i] = ConvertValue(
                        mRawValue.Substring(elemIndex, mRawValue.Length - elemIndex - 1),
                        elemType);

**Comment by cemdervis** [comment]
Thank you! It's fixed now.
