### ISSUE TITLE
.Net Core Support?

### ISSUE THREAD

**Issue by barbedCoil** [cemdervis/SharpConfig#70]
Having used this component in the past I wanted to see if it supports or will support .Net Core 2.x now or in the future?

If so, are there examples specifically for .Net Core or will this work in a different manner?

Thanks

**Comment by cemdervis** [comment]
The library is written to target .NET (I haven't tested it with .NET Core). However, everything should work out of the box with .NET Core. You'd just need to compile the library yourself, because I've not included binaries that target .NET Core (will do that in the future).

**Comment by cemdervis** [comment]
SharpConfig has been tested with .NET Core and is supported fully by it. I guess this issue is resolved.

**Comment by jiangjun0817** [comment]
@cemdervis Whether the last nuget version is supported .NET Core? When i install vs prompt "Package 'sharpconfig 3.2.6' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=2.0'. This package may not be fully compatible with your project'"

**Comment by barbedCoil** [comment]
Comment from @cemdervis from above:

_The library is written to target .NET (I haven't tested it with .NET Core). However, everything should work out of the box with .NET Core. **You'd just need to compile the library yourself**, because I've not included binaries that target .NET Core (will do that in the future)._

**Comment by cemdervis** [comment]
The 3.2.6 NuGet package does not support .NET Core. I've just published an updated package (version 3.2.6.1 on NuGet) that contains .NET Core binaries.
