### ISSUE TITLE
Can't read a path with a sharp (#)

### ISSUE THREAD

**Issue by CKoewing** [cemdervis/SharpConfig#72]
I have added a path-setting to my configuration and it works until the path-value contains a sharp (#).
In this case the path will be cut at the sharp, because SharpConfig identifies the rest as a comment.
This happens even if the path is written in quotation marks (example: "D:\Data\# Temp\Bin" => "D:\Data\").

**Comment by cemdervis** [comment]
It's correct that SharpConfig treats # as a comment char (see the static Configuration.PreferredCommentChar property). However, comment chars inside quoted values are ignored. Did you test this by reading a configuration file or are you creating configurations in code? You'd have to escape the value when creating it in code, e.g. `"\"D:\Data# Temp\Bin\""`.
If that's not the case and I'm missing something, maybe you could post an example configuration file?

**Comment by CKoewing** [comment]
It is an external config file.

Github has replaced a "\" behind the Data-Folder an before sharp ("D:\Data\# Temp\Bin"), here is the not working path "D:\Data\\# Temp\Bin" which becomes "D:\Data".

**Comment by cemdervis** [comment]
Alright, now it makes sense. I'll look into it.

**Comment by cemdervis** [comment]
Fixed with version 3.2.6. Thanks for finding this!
