### ISSUE TITLE
SaveToFile saves bool values with a capitral character

### ISSUE THREAD

**Issue by sebescudie** [cemdervis/SharpConfig#73]
When writing a config that has a boolean param, the value is saved as :

`MyValue=True`

Seems that the application can't then parse the file. Manually changing to `true` then works. 

Have I missed something ?
Thanks.

**Comment by lijian4607** [comment]
SharpConfig just use the string representation of System.Bool type.

And in this [source file](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/boolean.cs), it looks like:

internal const String TrueLiteral  = "True";

internal const String FalseLiteral = "False";

**Comment by cemdervis** [comment]
It should not matter whether it's `true`, `True` or even `TrUe`. When the string is parsed and converted to a bool, it's converted to a lower string first (see [here](https://github.com/cemdervis/SharpConfig/blob/master/SharpConfigShared/StockStringConverters.cs#L46)).

> Seems that the application can't then parse the file.

What exception do you get exactly?

**Comment by lijian4607** [comment]
@Sebescudie may refer to the application using other library instead of SharpConfig, even the WinAPI such as GetPrivateProfile and WritePrivateProfile.

**Comment by cemdervis** [comment]
Oh, that sounds reasonable @lijian4607. Can you confirm this, @sebescudie? If so, we could change SharpConfig to always save the value in lower case.

**Comment by lijian4607** [comment]
Maybe this feature should also be configurable, or all my configuration will be change when saving them.

**Comment by sebescudie** [comment]
Hi all. Sorry for answering that late. Turns out it was an error on my side : I was trying to write a default configuration file and read it at the same time. This is why after running the app a second time it worked (the app checks if the file exists before creating it). 

Didn't have anything to do with casing .. my bad !

**Comment by cemdervis** [comment]
Alright, seems reasonable. I'll close this issue then.
