### ISSUE TITLE
Method for mapping objects to configurations

### ISSUE THREAD

**Issue by noXur** [cemdervis/SharpConfig#8]
Hey there!

I recently started to use your library and I'm satifsfied with it so far. There is one question I want to ask.

**There is the very useful method for creating objects from configurations. Is there also a method which does the exact opposite?**

Greetings

**Comment by cemdervis** [comment]
Hey, thanks!

Something such as object serialization is not implemented yet, mainly because I hadn't thought about it yet. It should be fairly easy to implement, though. So that's a pretty good idea and I think I'll implement it later, if not tomorrow. Thanks again!

**Comment by noXur** [comment]
Thanks, too. That would be great. Otherwise, I have to write this method myself.

I will provide you feedback if it is implemented.

**Comment by cemdervis** [comment]
Hey, the new version is up (in the releases). Let me know what you think, thanks.

**Comment by noXur** [comment]
Nice! Works like it should. Thanks.

**Comment by noXur** [comment]
Hey, it's me again. I've recently started to use your library in Unity. Therefor it would be nice if your `Section.FromObject()` method would also support public fields in addition to public properties because in Unity, public fields are used for accessing data to support Unity's inspector serialization.

Otherwise, Unity users have to double their member code in order to use this method.

**Comment by noXur** [comment]
Hey. I don't know what happened to my last comment, seems to be vanished in the deeps of GitHub. So, I write it again.

I use your library within the Unity game engine now, it would be nice if the method `Section.FromObject()` would support also public fields for automatic (de-)serialization because Unity uses public fielfs rather than properties for its inspector serialization.

**Comment by cemdervis** [comment]
Oh, I see. I responded to your email yesterday but it also seems to have vanished. I've already fixed that issue, see the new version 1.4.5 :)

Cem
________________________________

**Comment by noXur** [comment]
Very nice!
