### ISSUE TITLE
UWP App UnauthorizedAccessException when I use SaveToFile

### ISSUE THREAD

**Issue by nathanieltabanao** [cemdervis/SharpConfig#88]
I am trying to save a config file from a UWP app.
This is my code
```
private void SaveButton_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
        {
            var user = new Configuration();
            string Email = txtEmail.Text.Trim();

             user[Email]["Value"].StringValue = "Test";

            string dest = Path.GetFullPath(@"D:\Test\user.cfg");
            user.SaveToFile(dest);
        }
```
When I reach at SaveToFile, I always get an UnauthorizedAccesException even when I already have the 

`broadAcess` permission, allowed the app to access the `FileSystem` on the privacy settings. I do not encounter this when I am creating `Console Apps`

**Comment by cemdervis** [comment]
This does not seem to be a SharpConfig issue. A workaround might be SaveToStream instead of SaveToFile. Ensure that you have the according rights for the stream.
