### ISSUE TITLE
Attribute to ignore field and property

### ISSUE THREAD

**Issue by e-lefort** [cemdervis/SharpConfig#9]
It would be great if we can ignore certain fields or properties by adding an attribute on top of it.

```csharp
class Person
{
    public string Name { get; set; }
    public int Age { get; set; }
    [Ignore]
    public int SomeField;
}
```

Currently I'm ussing the attribute [IgnoreDataMemberAttribute] available since .NET 3.0. It could be by creating a special attribute for SharpConfig to still support .NET 2.0.

Here the change I made in FromObject function

```csharp
foreach (var prop in type.GetProperties(BindingFlags.Instance | BindingFlags.Public))
{
    if (!prop.CanRead)
    {
        continue;
    }

    if (prop.GetCustomAttributes(typeof(IgnoreDataMemberAttribute), true).Length > 0)
    {
        continue;
    }

    object propValue = prop.GetValue(obj, null);
    Setting setting = new Setting(prop.Name, propValue != null ? propValue.ToString() : "");

    section.mSettings.Add(setting);
}

// Repeat for each public field.
foreach (var field in type.GetFields(BindingFlags.Instance | BindingFlags.Public))
{
    if (field.GetCustomAttributes(typeof(IgnoreDataMemberAttribute), true).Length > 0)
    {
        continue;
    }

    object fieldValue = field.GetValue(obj);
    Setting setting = new Setting(field.Name, fieldValue != null ? fieldValue.ToString() : "");

    section.mSettings.Add(setting);
}
```

**Comment by cemdervis** [comment]
That sounds good. Let me think about an ideal implementation.

**Comment by noXur** [comment]
In addition to this, an appropriate attribute for preventing (de-)serialization of certain public fields and properties during automatic object mapping/saving/loading would be nice, too. I would suggest `System.NonSerialized` for this purpose.

**Comment by cemdervis** [comment]
Wouldn't it be better to create a custom attribute for ignoring the (de)serialization?
Maybe an application wishes to not serialize some values somewhere, but wants SharpConfig to serialize them. If it never wants to serialize an attribute, it could just add both attributes to the field/property. E.g.:

[System.NonSerialized]
[SharpConfig.IgnoreSerialize]
public int MyProp { get; set; }

What do you think?

**Comment by noXur** [comment]
Sounds reasonable. :+1:
