### ISSUE TITLE
Add support for NULL keys

### ISSUE THREAD

**Issue by daemonPainter** [cemdervis/SharpConfig#90]
When reading an existing INI file, a NullReferenceException is thrown for empty keys. For instance:

```
[SECTION]
Name = ""
```

This file is not going to be loaded. Unfortunately, this is a real case scenario, and it would be nice to have the possibility to open the configuration anyway.

**Comment by cemdervis** [comment]
I was unable to reproduce this exception. The configuration is parsed fine.
