### ISSUE TITLE
Formal language grammar

### ISSUE THREAD

**Issue by khyew** [cemdervis/SharpConfig#92]
I'm interested in adding client libraries in other programming languages to read this configuration file format. Is there a documented formal grammar for SharpConfig (e.g. in BNF) that I could use to use as a starting point for a parser?

**Comment by hanabi1224** [comment]
@khyew TOML is designed on top of ini which has strict grammar spec

**Comment by cemdervis** [comment]
SharpConfig does not have a format on its own. It just parses configurations according to the ini/cfg specification.
