### ISSUE TITLE
Latest version 3.2.8 installed from NuGet doesn't contains static Configuration property "OutputRawStringValues"

### ISSUE THREAD

**Issue by LITTOMA** [cemdervis/SharpConfig#93]

**Comment by luisgustavocalsavara** [comment]
The SharpConfig.dll lib located in the BIN folder does not have the "OutputRawStringValues" property but recompiling the project, the generated lib is correct. But it is the wrong lib that is in Nuget.

**Comment by cemdervis** [comment]
Fixed with version 3.2.9.
